# Generated by Django 6.1.1 on 2026-09-18 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Unique Stock Keeping Unit or Barcode ID', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics & Appliances'), ('Pharmaceuticals', 'Pharmaceuticals & Healthcare'), ('Automotive Parts', 'Automotive & Spares'), ('Industrial Equipment', 'Industrial & Heavy Equipment'), ('FMCG', 'FMCG & Consumer Goods'), ('Textiles', 'Textiles & Apparel'), ('Chemicals & Materials', 'Chemicals & Raw Materials'), ('General Cargo', 'General Cargo / Parcels')], default='General Cargo', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(choices=[('Units', 'Units'), ('Boxes', 'Boxes'), ('Pallets', 'Pallets'), ('Cartons', 'Cartons'), ('Kg', 'Kilograms (Kg)'), ('Tons', 'Metric Tons')], default='Units', max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Declared goods value in INR', max_digits=12)),
                ('status', models.CharField(choices=[('Available', 'Available in Warehouse'), ('Issued', 'Issued for Dispatch'), ('In Transit', 'In Transit / On Route'), ('Delivered', 'Delivered to Destination'), ('Damaged', 'Damaged / Discrepancy')], default='Available', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('destination_hub_or_consignee', models.CharField(help_text='Receiving Center or Consignee Name', max_length=150)),
                ('destination_address', models.TextField()),
                ('destination_city', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=25)),
                ('dispatch_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Time shipment left the origin warehouse')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, help_text='Exact timestamp goods arrived at destination', null=True)),
                ('status', models.CharField(choices=[('Dispatched', 'Dispatched / In Transit'), ('Delivered', 'Delivered / Arrived'), ('Delayed', 'Delayed in Transit'), ('Cancelled', 'Cancelled')], default='Dispatched', max_length=30)),
                ('delivery_condition', models.CharField(blank=True, choices=[('Intact', 'Intact / Perfect Condition'), ('Minor Damage', 'Minor Packaging Wear'), ('Damaged', 'Damaged / Discrepancy Noted')], default='Intact', max_length=50)),
                ('received_by_signature_name', models.CharField(blank=True, help_text='Name of recipient confirming arrival', max_length=100, null=True)),
                ('arrival_notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-dispatch_time'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Container Truck', 'Container Truck (32 Ft)'), ('Medium Duty Truck', 'Medium Duty Truck (14-19 Ft)'), ('Mini Truck / Pickup', 'Mini Truck / Pickup (Tata Ace / Bolero)'), ('Refrigerated Reefer', 'Refrigerated Reefer Van'), ('Flatbed Carrier', 'Flatbed Heavy Carrier')], default='Container Truck', max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=25)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available in Yard'), ('In Transit', 'On Route / In Transit'), ('Maintenance', 'Under Maintenance')], default='Available', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Storage capacity (e.g., pallets/sq.ft)')),
                ('supervisor_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.PositiveIntegerField(default=1)),
                ('goods_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_records', to='logistics_app.goodsitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics_app.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='TransitCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=150)),
                ('status_note', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='logistics_app.shipment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics_app.vehicle'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_shipments', to='logistics_app.warehouse'),
        ),
        migrations.AddField(
            model_name='goodsitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='logistics_app.warehouse'),
        ),
        migrations.CreateModel(
            name='WarehouseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ADDED', 'Goods Added to Inventory'), ('UPDATED', 'Goods Details Updated'), ('ISSUED', 'Goods Issued for Shipment'), ('RECEIVED', 'Goods Arrived / Stock Received'), ('REMOVED', 'Goods Removed / Scrapped')], max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('goods_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logistics_app.goodsitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='logistics_app.warehouse')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
