# Generated by Django 6.1.1 on 2026-09-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('DISPATCH', 'Shipment Dispatched'), ('CHECKPOINT', 'Waypoint Passed'), ('ARRIVAL', 'Goods Arrived'), ('ENQUIRY', 'Customer Enquiry'), ('STOCK', 'Warehouse Inventory')], default='DISPATCH', max_length=30)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='dest_latitude',
            field=models.FloatField(default=18.5204, help_text='Destination GPS Latitude'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dest_longitude',
            field=models.FloatField(default=73.8567, help_text='Destination GPS Longitude'),
        ),
        migrations.AddField(
            model_name='transitcheckpoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transitcheckpoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.FloatField(default=19.076, help_text='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.FloatField(default=72.8777, help_text='GPS Longitude'),
        ),
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('In Progress', 'Under Investigation'), ('Resolved', 'Resolved & Answered')], default='Pending', max_length=30)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='logistics_app.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
