# Generated by Django 6.1.1 on 2026-09-18 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_notification_shipment_dest_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerenquiry',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='consumer',
            field=models.ForeignKey(blank=True, help_text='Linked consumer/consignee user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('DISPATCH', 'Shipment Dispatched'), ('CHECKPOINT', 'Waypoint Passed'), ('ARRIVAL', 'Goods Arrived'), ('ENQUIRY', 'Customer Enquiry'), ('REQUEST', 'Shipment Booking Request'), ('STOCK', 'Warehouse Inventory')], default='DISPATCH', max_length=30),
        ),
        migrations.CreateModel(
            name='ShipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics & Appliances'), ('Pharmaceuticals', 'Pharmaceuticals & Healthcare'), ('Automotive Parts', 'Automotive & Spares'), ('Industrial Equipment', 'Industrial & Heavy Equipment'), ('FMCG', 'FMCG & Consumer Goods'), ('Textiles', 'Textiles & Apparel'), ('Chemicals & Materials', 'Chemicals & Raw Materials'), ('General Cargo', 'General Cargo / Parcels')], default='General Cargo', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(choices=[('Units', 'Units'), ('Boxes', 'Boxes'), ('Pallets', 'Pallets'), ('Cartons', 'Cartons'), ('Kg', 'Kilograms (Kg)'), ('Tons', 'Metric Tons')], default='Units', max_length=20)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_address', models.TextField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved & Dispatched'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_requests', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_request', to='logistics_app.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROVIDER', 'Logistics Service Provider'), ('CONSUMER', 'Consumer / Consignee')], default='CONSUMER', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
