# Generated by Django 6.1.1 on 2026-09-18 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0003_customerenquiry_consumer_shipment_consumer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsitem',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Dealer/owner of this inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Logistics dealer/provider operating this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviced_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='preferred_provider',
            field=models.ForeignKey(blank=True, help_text='Specific provider requested by consumer (or null for any network dealer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_shipment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Registered commercial office address', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(blank=True, help_text='e.g. 3PL Logistics Dealer, Freight Forwarder, Fleet Owner, Retailer, Manufacturer', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gstin_or_tax_id',
            field=models.CharField(blank=True, help_text='Commercial Tax ID / GSTIN / Business Reg No.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Operating dealer/provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Operating dealer/provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or Business Name', max_length=150, null=True),
        ),
    ]
